
#define TGTT_BUFFER_BUFFERSIZE 1000
#define TGTT_BUFFER_LINESIZE 1001
#define TGTT_BUFFER_BORDERCOLOR 1002
#define TGTT_BUFFER_IO	1003

#define TGTT_BUFFER_IO_WRONLY 0
#define TGTT_BUFFER_IO_RDWR 1

#define TGTT_BUFFER_WRAP 1004


#define TGTA_BUFFER_ADD 1005

