
//#define TGT_CLASS_SELECTBOX 7

#define TGTT_SELECTBOX_ITEMS 1000
#define TGTT_SELECTBOX_POPFRAMECOLOR 1002
#define TGTT_SELECTBOX_POPSELCOLOR 1003
#define TGTT_SELECTBOX_SELECTED TGTT_GENERIC_VALUE
#define TGTT_SELECTBOX_MARK1 1005
#define TGTT_SELECTBOX_MARK2 1006
#define TGTT_SELECTBOX_ACTIVEBG TGTT_GENERIC_ACTIVEBG
