#define TGTT_STATUS_TEXT 1000
#define TGTT_STATUS_ALIGN 1001
#define TGTT_STATUS_TYPE 1002

#define TGT_STATUSF_ALLEFT 0
#define TGT_STATUSF_ALRIGHT 1
#define TGT_STATUSF_ATTACHED 0
#define TGT_STATUSF_ALIGNED 2
