#define TGTT_PROGRESS_CAPTION 1000
#define TGTT_PROGRESS_ACTIVEBG 1001
#define TGTT_PROGRESS_VALUE 1002
#define TGTT_PROGRESS_ENDVALUE 1003
#define TGTT_PROGRESS_TYPE 1004

#define TGT_PROGRESST_SHOWVALUE 1
#define TGT_PROGRESST_PERCENT 2
