
#define TGT_CLASS_LIST 5
#define TGTT_LIST_ITEMS 1000
#define TGTT_LIST_DATACALLBACK 1001
#define TGTT_LIST_REFRESHCALLBACK 1002
#define TGTT_LIST_SELECTED 1003
#define TGTT_LIST_FRAMECOLOR 1004
#define TGTT_LIST_ACTIVEBG 1005
#define TGTT_LIST_ACTIVEFG 1006


#define TGT_LISTREQ_GETMAX 1
#define TGT_LISTREQ_GETITEM 2


