
#define TGTT_BUFFER_BUFFERSIZE 1000
#define TGTT_BUFFER_LINESIZE 1001
#define TGTT_BUFFER_BORDERCOLOR TGTT_GENERIC_FRAMECOLOR
#define TGTT_BUFFER_IOMODE	1003

#define TGTT_BUFFER_IO_WRONLY 0
#define TGTT_BUFFER_IO_RDWR 1

#define TGTT_BUFFER_WRAP 1004


#define TGTA_BUFFER_ADD 1005
#define TGTA_BUFFER_ATTACHLAUNCHER 1006
#define TGTA_BUFFER_DETACHLAUNCHER 1007
