
//#define TGT_CLASS_LIST 5
#define TGTT_LIST_ITEMS 1000
#define TGTT_LIST_DATACALLBACK 1001
#define TGTT_LIST_REFRESHCALLBACK 1002
#define TGTT_LIST_SELECTED TGTT_GENERIC_VALUE
#define TGTT_LIST_FRAMECOLOR TGTT_GENERIC_FRAMECOLOR
#define TGTT_LIST_ACTIVEBG 1005
#define TGTT_LIST_ACTIVEFG 1006
#define TGTT_LIST_ZERO 1007
#define TGTT_LIST_ADJUST 1008
#define TGTT_LIST_CHANGECALLBACK 1009


#define TGT_LISTREQ_GETMAX 1
#define TGT_LISTREQ_GETITEM 2


